# Generated by Django 4.2.1 on 2023-08-08 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='名前')),
                ('page_size', models.PositiveSmallIntegerField(verbose_name='ページ数')),
                ('version', models.PositiveSmallIntegerField(verbose_name='版')),
            ],
            options={
                'verbose_name': '本',
                'verbose_name_plural': '本',
            },
        ),
        migrations.CreateModel(
            name='CommonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('creator', models.CharField(max_length=256, verbose_name='作者')),
                ('book', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='api.book', verbose_name='本')),
            ],
            options={
                'verbose_name': '詳細',
                'verbose_name_plural': '詳細',
            },
        ),
    ]
